name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run Docker
        run: |
          docker build -t my-app .

          docker stop my-app || true
          docker rm my-app || true

          docker run -d \
            --name my-app \
            -p 8080:8080 \
            --add-host=host.docker.internal:host-gateway \
            -e DB_HOST=host.docker.internal \
            -e DB_PORT=5432 \
            -e DB_USER=postgres \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=app_db \
            my-app
